<a href="https://colab.research.google.com/github/ramrajv/Upgrad_Pt_2/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [27]:
b2 = [[0.6,0],[0,0.8]]
M = np.linalg.inv(b2)
M

array([[1.66666667, 0.        ],
       [0.        , 1.25      ]])

In [28]:
v1 = [3,2]
v2 = M@v1

In [29]:
v2

array([5. , 2.5])

In [18]:
b2

[[-0.8, 0], [0, 0.6]]

In [30]:
phi = np.arctan(0.6/0.8)

In [35]:
M = np.array([[np.cos(phi),np.sin(phi)],[-1*np.cos(phi),np.sin(phi)]])

In [37]:
v2 = M@v1

In [38]:
v2

array([ 3.6, -1.2])